# `Ali Almalki`



## 🛠 00. TensorFlow Fundamentals Exercises
- Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
- Find the shape, rank and size of the tensors you created in 1.
- Create two tensors containing random values between 0 and 1 with shape [5, 300].
- Multiply the two tensors you created in 3 using matrix multiplication.
- Multiply the two tensors you created in 3 using dot product.
- Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
- Find the min and max values of the tensor you created in 6 along the first axis.
- Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
- Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
One-hot encode the tensor you created in 9.

#### Import Required Libraries

In [ ]:
# Import TensorFlow Library
import tensorflow as tf
# Import NumPy Library
import numpy as np

In [ ]:
# Check TensorFlow version
tf.__version__

'2.7.0'

In [ ]:
# Check physical devices
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

#### 1) Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [ ]:
scalar = tf.constant(4, 9)
scalar

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
scalar.shape, scalar.ndim

(TensorShape([]), 0)

In [ ]:
vector = tf.constant([10, 7])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
vector.shape, vector.ndim

(TensorShape([2]), 1)

In [ ]:
matrix = tf.constant([[10, 7],
                      [42, 89]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [42, 89]], dtype=int32)>

In [ ]:
t = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 21, 11],
                       [45, 11, 12]],
                      [[13, 56, 39],
                       [12, 44, 87]]])
t

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7, 21, 11],
        [45, 11, 12]],

       [[13, 56, 39],
        [12, 44, 87]]], dtype=int32)>

In [ ]:
t.shape, t.ndim

(TensorShape([3, 2, 3]), 3)

2) Find the shape, rank and size of the tensors you created in 1.

In [ ]:
print('The shape of the scalar:', scalar.shape)
print('The rank of the scalar:', np.array(tf.rank(scalar)))
print('The size of the scalar:', np.array(tf.size(scalar)))


The shape of the scalar: ()
The rank of the scalar: 0
The size of the scalar: 1


In [ ]:
print('The shape of the vector:', vector.shape)
print('The rank of the vector:', np.array(tf.rank(vector)))
print('The size of the vector:', np.array(tf.size(vector)))


The shape of the vector: (2,)
The rank of the vector: 1
The size of the vector: 2


In [ ]:
print('The shape of the matrix:', matrix.shape)
print('The rank of the matrix:', np.array(tf.rank(matrix)))
print('The size of the matrix:', np.array(tf.size(matrix)))

The shape of the matrix: (2, 2)
The rank of the matrix: 2
The size of the matrix: 4


In [ ]:
print('The shape of the Tensor:', t.shape)
print('The rank of the Tensor:', np.array(tf.rank(t)))
print('The size of the Tensor:', np.array(tf.size(t)))

The shape of the Tensor: (3, 2, 3)
The rank of the Tensor: 3
The size of the Tensor: 18


3) Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [ ]:
# Set global seed 
tf.random.set_seed(42)

t1 = tf.random.uniform(shape=([5, 300]))
t1

t2 = tf.random.uniform(shape=([5, 300]))
t2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
        0.9212563 ],
       [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
        0.51477313],
       [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
        0.9892651 ],
       [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
        0.8280058 ],
       [0.36690474, 0.9200133 , 0.9646884 , ..., 0.69012   , 0.7137332 ,
        0.2584542 ]], dtype=float32)>

In [ ]:
# Check tensors shape
t1.shape, t2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

4) Multiply the two tensors you created in 3 using matrix multiplication.

In [ ]:
tf.linalg.matmul(tf.transpose(t1), t2)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
        1.6227092 ],
       [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
        1.1739546 ],
       [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
        1.481925  ],
       ...,
       [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
        1.5979093 ],
       [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
        1.924531  ],
       [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
        1.0476992 ]], dtype=float32)>

In [ ]:
tf.transpose(t1).shape, t2.shape

(TensorShape([300, 5]), TensorShape([5, 300]))

5) Multiply the two tensors you created in 3 using dot product.

In [ ]:
tf.tensordot(tf.transpose(t1), t2, axes=1)

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.317161  , 0.61993605, 1.2612379 , ..., 1.5290778 , 1.0735596 ,
        1.6227092 ],
       [1.0170685 , 0.42642498, 0.8181824 , ..., 1.1469344 , 0.8212255 ,
        1.1739546 ],
       [0.45034647, 0.8037954 , 1.4656199 , ..., 1.105671  , 0.88152766,
        1.481925  ],
       ...,
       [1.3204696 , 1.1634867 , 1.7423928 , ..., 1.8386563 , 1.5207756 ,
        1.5979093 ],
       [0.73207504, 0.90400356, 1.8493464 , ..., 1.3821819 , 0.98218614,
        1.924531  ],
       [1.0814031 , 0.5316744 , 0.7174167 , ..., 1.2942287 , 1.0804075 ,
        1.0476992 ]], dtype=float32)>

6) Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [ ]:
tensor = tf.random.uniform(minval=0, maxval=1, shape=([224, 224, 3]))
print(tensor.shape)
print(tensor.ndim)
print(tf.size(tensor))
print(tensor)

(224, 224, 3)
3
tf.Tensor(150528, shape=(), dtype=int32)
tf.Tensor(
[[[0.7413678  0.62854624 0.01738465]
  [0.3431449  0.51063764 0.3777541 ]
  [0.07321596 0.02137029 0.2871771 ]
  ...
  [0.98953485 0.45382905 0.2006687 ]
  [0.6295223  0.4937899  0.01816809]
  [0.95386636 0.11542463 0.85691285]]

 [[0.78435016 0.7826872  0.87936425]
  [0.24906898 0.3207239  0.10955775]
  [0.543224   0.7151396  0.40334642]
  ...
  [0.2445668  0.01746976 0.9036933 ]
  [0.02975535 0.592268   0.9877522 ]
  [0.36701274 0.33112562 0.5638567 ]]

 [[0.15829337 0.7288823  0.3366307 ]
  [0.70792687 0.16910625 0.9429966 ]
  [0.10120225 0.5919596  0.8687303 ]
  ...
  [0.28134012 0.10011208 0.37038183]
  [0.77874243 0.05421627 0.4664607 ]
  [0.2549187  0.7968637  0.83405185]]

 ...

 [[0.32922816 0.06343532 0.23936498]
  [0.42692196 0.3615111  0.901929  ]
  [0.8320831  0.21068895 0.08272386]
  ...
  [0.65110314 0.40780962 0.25967455]
  [0.9018173  0.8245677  0.16757596]
  [0.41854453 0.19092035 0.2523303 ]]

 [[0.7

7) Find the min and max values of the tensor you created in 6 along the first axis.

In [ ]:
# Find the minimum value along the first axis
np.array(tf.reduce_min(tensor))

array(2.3841858e-07, dtype=float32)

In [ ]:
# Find the maximum value along the first axis
np.array(tf.reduce_max(tensor))

array(0.9999918, dtype=float32)

8) Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [ ]:
tesnor = tf.random.uniform(shape=([1, 224, 224, 3]))
tesnor

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[7.4023080e-01, 3.3938193e-01, 5.6925058e-01],
         [4.4811392e-01, 2.9285502e-01, 4.2600560e-01],
         [6.2890387e-01, 6.9106102e-01, 3.0925727e-01],
         ...,
         [9.1063976e-04, 6.9863999e-01, 1.7180574e-01],
         [6.7542684e-01, 8.3492923e-01, 3.9038682e-01],
         [2.3664141e-01, 6.2239432e-01, 1.0117912e-01]],

        [[9.7064960e-01, 5.4594779e-01, 7.6819682e-01],
         [2.6893330e-01, 2.6959443e-01, 2.8982997e-01],
         [2.9215467e-01, 1.7108858e-01, 6.5597153e-01],
         ...,
         [9.5621395e-01, 5.4591870e-01, 5.3843534e-01],
         [9.8861516e-01, 1.5786767e-01, 6.1375093e-01],
         [7.2668612e-01, 6.1637163e-03, 1.6534305e-01]],

        [[6.4095867e-01, 7.6697862e-01, 3.0138540e-01],
         [1.5474892e-01, 1.7183411e-01, 2.7192724e-01],
         [3.1211805e-01, 6.1451709e-01, 4.3001354e-01],
         ...,
         [8.4168065e-01, 5.0247252e-01, 2.8834987e-01],


In [ ]:
# Squeeze the  tesnor
tf.squeeze(tensor)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

10) Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [ ]:
t = tf.constant([4, 8, 2, 87, 42, 178, 29, 343, 27, 101])
print('Tensor shape:', t.shape)

Tensor shape: (10,)


In [ ]:
# Find the index which has the maximum value
tf.math.argmax(t)

<tf.Tensor: shape=(), dtype=int64, numpy=7>

In [ ]:
t[7]

<tf.Tensor: shape=(), dtype=int32, numpy=343>

In [ ]:
# Find the index which has the minimum value
tf.argmin(t)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
t[2]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

10) One-hot encode the tensor you created in 9.

In [ ]:
tf.one_hot(t, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### References: 
- TensorFlow Documentation: https://www.tensorflow.org/api_docs/python/tf/all_symbols
- Exercise Source: https://github.com/mrdbourke/tensorflow-deep-learning#-00-tensorflow-fundamentals-exercises